apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudforge-config
  namespace: cloudforge-system
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/cloudforge"
  SPRING_DATA_REDIS_HOST: "redis-service"
  SPRING_DATA_REDIS_PORT: "6379"
  CLOUDFORGE_CORS_ALLOWED_ORIGINS: "http://cloudforge.local"
